Repository TechUniv2018/social-credit, pull requests merged in 2018-03, with the labels that each got.

#92 Code Review: Issue 90: Migration and model for twitters table added.
  migrations/20180226163640-create-twitters.js
  models/twitters.js
  package-lock.json
  package.json
  seeders/20180302165750-seed-facebook-users.js
  src/routes/api/max-amount.js
  src/routes/api/users/loans.js
  test/routes/api/max-amount.test.js
  test/routes/api/users/loans.test.js
Labels: review

#101 Code Review: Issue 17: Loan Functionality: Create API for request for loan
  package.json
  seeders/20180207121247-sample-loans.js
  src/routes/api/users/loans.js
  test/routes/api/users/loans.test.js
Labels: review

#72 Code Review: Issue 64: Enable SSL for production db
  config/config.js
Labels: review

#98 Code Review: Issue 96: Refactor: Remove unused routes and add tests for login
  seeders/20180205164933-seed-sample-users.js
  src/server.js
  test/routes/api/users/login.test.js
  test/server.test.js
Labels: review

#106 Code Review: Issue 102: Loan Functionality: Add EMI details in response
  migrations/20180308121816-update-loan-id-type-emi-table.js
  models/emi.js
  models/facebook.js
  models/loans.js
  models/user.js
  seeders/20180207121247-sample-loans.js
  seeders/20180308185522-seed-emi-entries.js
  src/routes/api/users/loans.js
Labels: backend, review

#105 Code Review: Issue 103: Loan Lending Book: Admin gets all the loans details in lending book
  package-lock.json
  src/routes/api/admin/index.js
  src/routes/api/admin/loans.js
  src/routes/index.js
  test/routes/api/admin/loans.test.js
Labels: backend, review

#107 Code Review: Issue 16: Loan Functionality: Create an API to pay EMI
  seeders/20180207121247-sample-loans.js
  seeders/20180302165750-seed-facebook-users.js
  seeders/20180308185522-seed-emi-entries.js
  src/routes/api/user/emi.js
  src/routes/api/users/emi.js
  src/routes/api/users/index.js
  src/routes/api/users/loans.js
  src/server.js
  test/routes/api/users/emi.test.js
Labels: backend, review

#108 Code Review: Issue 10: Define a formula to calculate the maximum eligible loan
  src/routes/api/users/loans.js
  test/routes/api/users/loans.test.js
Labels: backend, review

#111 Code Review: Issue 110: Export maximum eligible amount as a helper function
  src/lib/loan-helpers.js
  src/routes/api/users/loans.js
  test/lib/loan-helpers.test.js
Labels: refactor, review

#109 Code Review: Issue104: Calculate social score: Integrate Twitter into project
  package-lock.json
  package.json
  seeders/20180205164933-seed-sample-users.js
  seeders/20180302165750-seed-facebook-users.js
  seeders/20180302165751-seed-twitter-users.js
  src/lib/twitter-config.json
  src/lib/twitter-helpers.js
  src/routes/api/users/index.js
  src/routes/api/users/twitter.js
  test/lib/twitter-helpers.test.js
  test/lib/user-helpers.test.js
  test/routes/api/users/loans.test.js
  test/routes/api/users/twiter.test.js
Labels: review

#112 Code Review: Issue 95: Dashboard: Show social score breakdown
  .vscode/launch.json
  package-lock.json
  package.json
  seeders/20180302165750-seed-facebook-users.js
  src/lib/twitter-helpers.js
  src/routes/api/users/info.js
  test/lib/twitter-helpers.test.js
  test/routes/api/max-amount.test.js
  test/routes/api/users/__snapshots__/info.test.js.snap
  test/routes/api/users/info.test.js
  test/routes/api/users/loans.test.js
Labels: review

#113 Code Review Issue 5: Hotfix: Scores are added instead of being averaged
  src/routes/api/users/twitter.js
Labels: review

#115 Code Review: Issue 114: Refactor: Add maximum eligible loan amount in GET /api/users/info
  src/lib/loan-helpers.js
  src/routes/api/users/info.js
  test/lib/loan-helpers.test.js
  test/routes/api/users/__snapshots__/info.test.js.snap
  test/routes/api/users/info.test.js
Labels: review

#117 Code Review: Issue 116: Calculate social score: Hotfix: Change seeders
  seeders/20180205164933-seed-sample-users.js
Labels: review

#119 Code Review: Issue 118: Update swagger tags
  src/routes/api/admin/loans.js
  src/routes/api/max-amount.js
  src/routes/api/users/info.js
  src/routes/api/users/loans.js
  src/routes/api/users/login.js
  src/routes/api/users/twitter.js
Labels: backend, refactor, review

#122 Code Review: Issue 104: Integrate twitter into project
  models/twitters.js
  package-lock.json
  package.json
  src/lib/twitter-helpers.js
  src/routes/api/auth/index.js
  src/routes/api/auth/twitter.js
  src/routes/api/users/info.js
  src/routes/api/users/loans.js
  src/routes/api/users/twitter.js
  src/routes/index.js
  src/server.js
  test/lib/twitter-helpers.test.js
  test/routes/api/users/__snapshots__/info.test.js.snap
  test/routes/api/users/loans.test.js
Labels: review

#126 Code Review: Issue 124: Dashboard: Fix bugs
  src/lib/loan-helpers.js
  src/lib/twitter-helpers.js
  src/routes/api/users/info.js
  test/lib/loan-helpers.test.js
  test/routes/api/users/__snapshots__/info.test.js.snap
Labels: review

#121 Code Review: Issue 120: Dashboard: Show social graph
  src/lib/twitter-helpers.js
  src/routes/api/users/index.js
  src/routes/api/users/info.js
  src/routes/api/users/twitterGraph.js
  test/routes/api/users/__snapshots__/info.test.js.snap
  test/routes/api/users/info.test.js
Labels: review
